spring:
  security:
    jwt:
      secret-key: ${SECURITY_JWT_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
  zipkin:
    baseUrl: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}
  application:
    name: shop-gateway

  # cloud:
  #   gateway:
  #     default-filters:
  #     - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  #     globalcors:
  #       cors-configurations:
  #         '[/**]':
  #          allowedOrigins: "*"
  #          allowedMethods: "*"
  #          allowedHeaders: "*"
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://192.168.1.19:4200"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
      routes:
        - id: Customer Login
          uri: http://192.168.1.19:8998
          predicates:
            - Path=/api/user/login
        - id: Me
          uri: http://192.168.1.19:8998
          predicates:
            - Path=/api/user/me
        - id: Customer Registration
          uri: http://192.168.1.19:8998
          predicates:
            - Path=/api/user/register
        - id: Catalog
          uri: http://192.168.1.19:8082
          predicates:
            - Path=/catalog
        - id: Cart
          uri: http://192.168.1.19:7500
          predicates:
            - Path=/api/cart/**
        - id: Purchase
          uri: http://192.168.1.19:7500
          predicates:
            - Path=/api/orders/**
            
        # - id: MyCart
        #   uri: http://192.168.1.19:7500
        #   predicates:
        #     - Path=/api/cart/mycart

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 9999

#Zipkin config
management:
  tracing:
    sampling:
      probability: 1.0
  #Actuator config
  endpoints:
    web:
      exposure:
        include: "*"
